use_frameworks!

target 'KRMathInputView_Example' do
  pod 'KRMathInputView', :git => 'https://github.com/BridgeTheGap/KRMathInputView.git'
    
    target 'KRMathInputView_ExampleTests' do
    inherit! :search_paths
    end

end
